# This configuration uses 'http' and is not recommended for production use.
# Refer https://istio.io/latest/docs/tasks/observability/gateways/ for a more secure 'https' config
# using a self signed certificate and prefer that for production use
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: grafana-observability-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - grafana.istio-system.34.76.233.160.nip.io
    - port:
        number: 80
        name: http2
        protocol: HTTP2
      hosts:
        - grafana.istio-system.34.76.233.160.nip.io
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-gw-virtualservice
  namespace: istio-system
spec:
  hosts:
    - grafana.istio-system.34.76.233.160.nip.io
  gateways:
    - grafana-observability-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: grafana
